name: medilink
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.20.2
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.0 # OR RIVE
  mapbox_search: ^4.3.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  shared_preferences: ^2.5.2
  flutter_svg: ^2.1.0
  mapbox_maps_flutter: ^2.6.2
  permission_handler: ^11.4.0
  flutter_dotenv: ^5.2.1
  intl_utils: ^2.8.10
  geolocator: ^13.0.3
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  connectivity_plus: ^6.1.4
  google_sign_in: ^7.1.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.10
  cached_network_image: ^3.4.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  location: ^8.0.1
  table_calendar: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/images/reviews/
    - assets/logos/
    - assets/data/states_cities.json


    - assets/icons/services/
    - assets/doctors/
    - assets/icons/specialties/
    - assets/icons/categories/
    - assets/data/
    - assets/images/medicines/
    - assets/clinics/
    - .env
  #-------------------------- local fonts --------------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
flutter_intl:
  enabled: true
